version: '3'
services:
  app:
    build:
      context: .
      target: build
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0

